// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-hY1C6U4onfqy73j5HglwtN5BtqQNoFw',
    appId: '1:397433355252:android:aff3765b990edb180857a1',
    messagingSenderId: '397433355252',
    projectId: 'mobiking-25fc3',
    storageBucket: 'mobiking-25fc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLfnDnqJ3LDp9NgMA0VqJ2yE-AFm9tgdE',
    appId: '1:397433355252:ios:d22edbf2a925e6ac0857a1',
    messagingSenderId: '397433355252',
    projectId: 'mobiking-25fc3',
    storageBucket: 'mobiking-25fc3.firebasestorage.app',
    iosBundleId: 'com.example.mobiking',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2cD8s816pK1xC_zSI4eGG_Yjro8X_Gm4',
    appId: '1:397433355252:web:cc8c08179b3ad2c10857a1',
    messagingSenderId: '397433355252',
    projectId: 'mobiking-25fc3',
    authDomain: 'mobiking-25fc3.firebaseapp.com',
    storageBucket: 'mobiking-25fc3.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLfnDnqJ3LDp9NgMA0VqJ2yE-AFm9tgdE',
    appId: '1:397433355252:ios:d22edbf2a925e6ac0857a1',
    messagingSenderId: '397433355252',
    projectId: 'mobiking-25fc3',
    storageBucket: 'mobiking-25fc3.firebasestorage.app',
    iosBundleId: 'com.example.mobiking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2cD8s816pK1xC_zSI4eGG_Yjro8X_Gm4',
    appId: '1:397433355252:web:9599c9d3971c62720857a1',
    messagingSenderId: '397433355252',
    projectId: 'mobiking-25fc3',
    authDomain: 'mobiking-25fc3.firebaseapp.com',
    storageBucket: 'mobiking-25fc3.firebasestorage.app',
  );

}